[build]
  # Build command for Storybook (install devDeps explicitly for Storybook build tools)
  command = "npm ci --production=false && npm run build-storybook"
  
  # Output directory (where Storybook builds to)
  publish = "storybook-static"

[build.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_APP_ENV = "development"
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-key"
  CSRF_SECRET = "placeholder-secret-for-storybook"

# Headers for better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect for Storybook
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200