name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.{js,jsx,ts,tsx}
          files_ignore: |
            **/*.test.{js,jsx,ts,tsx}
            **/*.spec.{js,jsx,ts,tsx}
            **/*.stories.{js,jsx,ts,tsx}

      - name: AI Code Review
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get changed files
            const changedFiles = process.env.CHANGED_FILES.split(' ');
            
            let reviewComments = [];
            
            for (const file of changedFiles) {
              if (!fs.existsSync(file)) continue;
              
              const content = fs.readFileSync(file, 'utf8');
              const lines = content.split('\n');
              
              // Basic automated review checks
              lines.forEach((line, index) => {
                const lineNum = index + 1;
                
                // Check for console.log
                if (line.includes('console.log') && !line.includes('// eslint-disable')) {
                  reviewComments.push({
                    path: file,
                    line: lineNum,
                    body: '🚨 **Code Quality**: Consider using the secure logger instead of console.log for production code.\n\n```suggestion\nimport { secureLogger } from \'@/lib/secure-logger\';\nsecureLogger.info(/* your message */);\n```'
                  });
                }
                
                // Check for any type
                if (line.includes(': any') && !line.includes('// @ts-')) {
                  reviewComments.push({
                    path: file,
                    line: lineNum,
                    body: '🔍 **Type Safety**: Consider using a more specific type instead of `any` to improve type safety.'
                  });
                }
                
                // Check for TODO comments
                if (line.includes('TODO') || line.includes('FIXME')) {
                  reviewComments.push({
                    path: file,
                    line: lineNum,
                    body: '📝 **Technical Debt**: TODO/FIXME comment found. Consider creating a GitHub issue to track this work.'
                  });
                }
                
                // Check for hardcoded strings that might need i18n
                if (line.match(/["']([A-Z][a-z\s]{10,})["']/)) {
                  reviewComments.push({
                    path: file,
                    line: lineNum,
                    body: '🌐 **Internationalization**: Consider if this user-facing text should be moved to a translation file.'
                  });
                }
                
                // Check for missing error handling
                if (line.includes('await ') && !content.includes('try') && !content.includes('catch')) {
                  reviewComments.push({
                    path: file,
                    line: lineNum,
                    body: '⚠️ **Error Handling**: Consider adding proper error handling for async operations.'
                  });
                }
              });
            }
            
            // Post review comments
            if (reviewComments.length > 0) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                comments: reviewComments.slice(0, 10), // Limit to 10 comments
                event: 'COMMENT'
              });
            }
            
            // Post summary comment
            const consoleLogCount = reviewComments.filter(c => c.body.includes('console.log')).length;
            const typeIssueCount = reviewComments.filter(c => c.body.includes('any')).length;
            const todoCount = reviewComments.filter(c => c.body.includes('TODO')).length;
            
            let summaryComment = '## 🤖 AI Code Review Summary\\n\\n';
            summaryComment += '**Files analyzed**: ' + changedFiles.length + '\\n';
            summaryComment += '**Issues found**: ' + reviewComments.length + '\\n\\n';
            summaryComment += '### Quick Stats:\\n';
            summaryComment += '- Console.log statements: ' + consoleLogCount + '\\n';
            summaryComment += '- Type safety issues: ' + typeIssueCount + '\\n';
            summaryComment += '- TODO/FIXME items: ' + todoCount + '\\n\\n';
            
            if (reviewComments.length === 0) {
              summaryComment += '✅ **Great job!** No automated issues detected.\\n';
            }
            
            if (reviewComments.length > 10) {
              summaryComment += '⚠️ **Note**: Only showing first 10 issues. Total found: ' + reviewComments.length + '\\n';
            }
            
            summaryComment += '\\n---\\n*Automated review by GitHub Actions*';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summaryComment
            });
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}