name: Debug Workflow Syntax

on:
  push:
    branches: [fix/vercel-build-errors]

jobs:
  debug-sonar:
    name: Debug SonarCloud Step
    runs-on: ubuntu-latest
    
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: secrets.SONAR_TOKEN != ''
        with:
          args: >
            -Dsonar.javascript.eslint.reportPaths=eslint-report.json
            -Dsonar.qualitygate.wait=true
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true