name: Deploy Storybook

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/components/**'
      - 'src/stories/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'
      - 'public/**'
      - '.gitignore'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/components/**'
      - 'src/stories/**'
      - '.storybook/**'
  workflow_dispatch:

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_ENV: production
        
      - name: Install Vercel CLI
        run: npm i -g vercel@canary
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./storybook-static
        
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./storybook-static
        
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = process.env.VERCEL_URL || 'https://storybook-static-jasper-lepardos-projects.vercel.app';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎨 **Storybook Preview**: ${deployment}\n\nComponent library has been updated and deployed automatically.`
            });