name: Deploy Storybook

on:
  push:
    branches: [develop]
    paths:
      - 'src/components/**'
      - 'src/stories/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'
      - 'public/**'
      - '.gitignore'
  workflow_dispatch:

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          cd storybook-static
          echo "Storybook built successfully. Manual deployment required."
          echo "Run: vercel --prod --yes to deploy"
          echo "Or use existing deployment at: https://citizenly-storybook-pu6qrpcz8-jasper-lepardos-projects.vercel.app"