name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security checks
        run: npm run security:check

      - name: Run tests
        run: npm run test:ci

      - name: Run type check
        run: npm run type-check

      - name: Run lint
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Validate commit messages
        run: |
          # Check if commits follow conventional commit format
          git log --format="%s" origin/${{ github.base_ref }}..${{ github.sha }} | \
          grep -E "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(\(.+\))?: .+" || \
          (echo "❌ Commits must follow conventional commit format" && exit 1)

      - name: Comment PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All checks passed! This pull request is ready for review.'
            })