name: Release

# Note: VS Code may show warnings about "Context access might be invalid" for NPM_TOKEN.
# This is an expected warning for optional npm publishing.
# The workflow will work correctly with or without NPM_TOKEN configured.

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security checks
        run: npm run security:check

      - name: Run tests
        run: npm run test:ci

      - name: Run type check
        run: npm run type-check

      - name: Run lint
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Run SonarCloud quality gate
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN || '' }}
        continue-on-error: true
        with:
          args: >
            -Dsonar.qualitygate.wait=true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN || '' }}
        run: npm run release
        continue-on-error: true